In [ ]:
my_number = 50
print (my_number)
print (type(my_number))

50
<class 'int'>


In [ ]:
total = 70
print (total)
print(type(total))

70
<class 'int'>


In [ ]:
weight = 40.5
print (weight)
print(type(weight))

40.5
<class 'float'>


In [ ]:
My_name = "I am anitha"
print (My_name)
print (type(My_name))

I am anitha
<class 'str'>


In [ ]:
Collage = "APC MAHALAXMI COLLAGE"
print (Collage)
print (type(Collage))

APC MAHALAXMI COLLAGE
<class 'str'>


In [ ]:
67<89

True

In [ ]:
Marks = 100
if pass >=35
  print

In [ ]:
friends_li= ['Ani','karthika','priya','maha']
print(friends_li)

['Ani', 'karthika', 'priya', 'maha']


In [ ]:
for i in friends_li:
    print(i)

Ani
karthika
priya
maha


In [ ]:
marks_li = [76,98,54,43,96,21,45]
print( marks_li)

[76, 98, 54, 43, 96, 21, 45]


In [ ]:
for i in marks_li:
 if i>=35:
  print('passed',i,'marks scored')
else:
  print('failed',i,'marks scored')

passed 76 marks scored
passed 98 marks scored
passed 54 marks scored
passed 43 marks scored
passed 96 marks scored
passed 45 marks scored
failed 45 marks scored


In [ ]:

import numpy as np
my_list = [6,7,8,9,2]
my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[6 7 8 9 2]
<class 'numpy.ndarray'>


In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
a = [1,3,5]
b = [2,7,6]
a + b

[1, 3, 5, 2, 7, 6]

In [ ]:
a = np.array([1,3,5])
b = np.array([2,7,6])
a + b

array([ 3, 10, 11])

In [ ]:
np.arange(5,99)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Val = np.random.randint(1,100,10)
Val

array([66, 59,  9, 35, 81, 86, 17, 40, 83, 26])

In [ ]:
random_arr = np.random.randn(3)
random_arr

array([-0.1125955 ,  1.58420127, -0.92668224])

In [ ]:
towD_arr = np.

In [63]:
data = [23,45,67,88,66,32,43]
data[1]%2==0

False

In [64]:
arr = np.array([10,20,48,52,58,45,69,36])
print(arr >25)

[False False  True  True  True  True  True  True]


In [65]:
arr[arr%2 == 0]

array([10, 20, 48, 52, 58, 36])